name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Pull LFS files
        run: git lfs pull
      - name: Install huggingface_hub
        run: pip install huggingface_hub
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - <<EOF
          from huggingface_hub import HfApi
          api = HfApi()
          api.upload_folder(
              folder_path=".",
              repo_id="mahraalh/cola-pepsi-detection",
              repo_type="space",
              token="${{ secrets.HF_TOKEN }}",
              ignore_patterns=[".git*", ".github*"]
          )
          EOF